spring:
  datasource:
    url: jdbc:mysql://${CONFIG_MYSQL_SERVER}/${CONFIG_MYSQL_DB_NAME}
    username: ${CONFIG_MYSQL_USERNAME}
    password: ${CONFIG_MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  output:
    ansi:
      enabled: ALWAYS #enables colored log output

logging:
  level:
    root: ${ROOT_LOG_LEVEL}
    be.pbin.readserver: ${APPLICATION_LOG_LEVEL}

azurite:
  service:
    key: ${CONFIG_AZURITE_ACCOUNT_KEY}
    connection: DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=
    account: ${CONFIG_AZURITE_ACCOUNT_NAME}
    url: ${CONFIG_AZURITE_URL}
    container: ${CONFIG_AZURITE_ACCOUNT_NAME}