server:
  address:
    localhost
  port:
    8003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: password
#    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
  jackson:
    deserialization:
      fail-on-unknown-properties: true