server:
  address:
    localhost
  port:
    8002

spring:
  output:
    ansi:
      enabled: ALWAYS #enables colored log output

logging:
  level:
    root: DEBUG
    be.pbin.webserver: DEBUG

be:
  pbin:
    write-server:
      base-url: "http://localhost:8003"
      path: "/api/save"
    read-server:
      base-url: "http://localhost:8004"
      path: "/api/get"
