# WEBSERVER

spring:
  output.ansi.enabled: ALWAYS #enables colored log output
  jackson:
    deserialization:
      fail-on-unknown-properties: true


logging:
  level:
    root: ${ROOT_LOG_LEVEL}
    be.pbin.webserver: ${APPLICATION_LOG_LEVEL}

be:
  pbin:
    write-server:
      base-url: ${WRITESERVER_URL}
      path: "/api/note"
    read-server:
      base-url: ${READSERVER_URL}
      path: "/api/note"

server:
  error:
    whitelabel.enabled: false