# WEBSERVER - Configuration for a local build

spring:
  output.ansi.enabled: ALWAYS #enables colored log output
  jackson:
    deserialization:
      fail-on-unknown-properties: true


logging:
  level:
    root: info
    be.pbin.webserver: info

be:
  pbin:
    write-server:
      base-url: "http://localhost:8003"
    read-server:
      base-url: "http://localhost:8004"

server:
  port: 8002
  error:
    whitelabel.enabled: false